export const AUTH = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
};
export const INVOICES = {
  GET_INVOICE: 'GET_INVOICE',
  CREATE_INVOICE: 'CREATE_INVOICE',
};
export default AUTH;
